// scripts/inject-version.js
//
// Injects version string into version.js for content scripts.
//   debug   → git commit hash (e.g. "6774ea7")
//   release → manifest version with v-prefix (e.g. "v5.0.3")
//
// Usage: node scripts/inject-version.js [debug|release]
// Env:   XD_BUILD_MODE=debug  (fallback when no CLI arg)
//
// In debug mode, also patches manifest.json version to the commit hash
// so that web-ext build produces filenames with the hash instead of semver.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const mode = process.argv[2] || process.env.XD_BUILD_MODE || 'release';
const versionPath = path.join(__dirname, '..', 'version.js');
const manifestPath = path.join(__dirname, '..', 'manifest.json');

let versionString = '';

if (mode === 'debug') {
    try {
        versionString = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
    } catch (e) {
        console.warn('Could not get git commit hash:', e.message);
    }
} else {
    const manifestCommonPath = path.join(__dirname, '..', 'manifest.common.json');
    const manifest = require(manifestCommonPath);
    const v = manifest.version || '0.0.0';
    versionString = 'v' + v;
}

const content = `// Auto-generated by inject-version.js — DO NOT EDIT
window.xdAnswers = window.xdAnswers || {};
window.xdAnswers._buildVersion = '${versionString}';
`;

fs.writeFileSync(versionPath, content, 'utf-8');

// In debug mode, patch manifest.json version so web-ext produces hash-based filenames
if (mode === 'debug' && versionString && fs.existsSync(manifestPath)) {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    manifest.version = versionString;
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
    console.log(`Patched manifest.json version to ${versionString}`);
}

console.log(`Injected ${mode} version: ${versionString || '(unknown)'}`);
