# Назва нашого workflow, яка буде відображатися на вкладці "Actions" в GitHub
name: Build Extension on Push

# Умова запуску: workflow активується при push у гілку main
on:
  push:
    branches:
      - main # Запускати тільки для гілки main. Можна додати інші, наприклад: [ main, master ]

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Крок для отримання версії з manifest.json (залишаємо, може бути корисним)
      - name: Get extension version from manifest
        id: get_version
        run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

      - name: Build for Firefox
        run: npm run build:firefox # Ця команда має створювати архів у папці ./build

      # Пакуємо розширення для Chrome
      - name: Package for Chrome
        run: |
          mkdir chrome_package
          cp manifest.json chrome_package/
          cp background.js chrome_package/
          cp content.js chrome_package/
          cp popup.html chrome_package/
          cp popup.js chrome_package/
          cp popup.css chrome_package/
          cp -r images chrome_package/
          # Додайте сюди інші файли/папки, якщо вони є частиною розширення
          cd chrome_package
          zip -r ../chrome-extension.zip .
          cd ..

      # Визначаємо шлях до зібраного файлу Firefox
      - name: Get Firefox artifact path
        id: get_firefox_path
        run: |
          firefox_artifact_path=$(ls -1 build/*.zip | head -n 1)
          if [ -z "$firefox_artifact_path" ]; then
            echo "::error::Firefox artifact (.zip) not found in build/ directory."
            exit 1
          fi
          echo "path=$firefox_artifact_path" >> $GITHUB_OUTPUT
          echo "Found Firefox artifact: $firefox_artifact_path"

      # ЗБЕРІГАЄМО АРТЕФАКТИ
      # Замість завантаження у реліз, зберігаємо зібрані файли як артефакти цього workflow
      - name: Upload Chrome Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ steps.get_version.outputs.version }} # Назва артефакту
          path: chrome-extension.zip # Шлях до файлу для завантаження

      - name: Upload Firefox Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-${{ steps.get_version.outputs.version }} # Назва артефакту
          path: ${{ steps.get_firefox_path.outputs.path }} # Шлях до файлу Firefox