name: Debug

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build extensions for Firefox and Chrome
        run: |
          npm run build:firefox
          npm run build:chrome

      - name: Get Firefox artifact path
        id: get_firefox_path
        run: |
          firefox_artifact_path=$(find build -name "*.zip" -o -name "*.xpi" | head -n 1)
          if [ -z "$firefox_artifact_path" ]; then
            echo "::error::Firefox artifact (.zip or .xpi) not found in build/ directory."
            exit 1
          fi
          echo "path=$firefox_artifact_path" >> $GITHUB_OUTPUT

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: xdAnswers-firefox
          path: ${{ steps.get_firefox_path.outputs.path }}

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: xdAnswers-chrome
          path: ./build/xdAnswers-chrome.zip