name: Create Release and Upload Assets

# Умова запуску: workflow активується при створенні нового тегу, що починається з "v"
on:
  push:
    tags:
      - 'v*' # Наприклад, v1.0, v1.2.3, v2.0-beta

jobs:
  build-and-release:
    permissions:
      contents: write # Потрібен дозвіл на створення релізу та завантаження файлів
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Завантажуємо всю історію, щоб отримати доступ до всіх тегів та комітів
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # Використовуємо npm install, оскільки немає package-lock.json
        run: npm install

      - name: Build extensions for Firefox and Chrome
        # Тепер ми просто запускаємо npm-скрипти, які роблять всю роботу
        run: |
          npm run build:firefox
          npm run build:chrome
        
      # КРОК 1: Генеруємо опис для релізу на основі історії комітів
      - name: Generate Release Body
        id: generate_release_body
        run: |
          # Отримуємо попередній тег. Якщо його немає, беремо перший коміт в історії.
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 "tags/${{ github.ref_name }}~1" 2>/dev/null || git rev-list --max-parents=0 HEAD)
          echo "Previous tag: $PREVIOUS_TAG"
          
          # Створюємо список комітів у потрібному форматі: "* назва (id)"
          CHANGELOG=$(git log $PREVIOUS_TAG...${{ github.ref_name }} --pretty=format:'* %s (%h)')
          
          # Офіційний спосіб передачі багаторядкового тексту в GitHub Actions
          {
            echo 'changelog<<EOF'
            echo "$CHANGELOG"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # КРОК 2: Створюємо сам реліз на GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} # Використовуємо тег, що запустив workflow
          release_name: Release ${{ github.ref_name }} # Назва релізу, напр. "Release v1.0.1"
          body: ${{ steps.generate_release_body.outputs.changelog }} # Використовуємо згенерований список комітів
          draft: false # Якщо true, реліз буде чернеткою
          prerelease: false # Якщо true, реліз буде позначено як "pre-release"

      # Визначаємо шлях до зібраного файлу Firefox
      - name: Get Firefox artifact path
        id: get_firefox_path
        run: |
          # web-ext створює архів у папці build, знаходимо його
          firefox_artifact_path=$(find build -name "*.zip" -o -name "*.xpi" | head -n 1)
          if [ -z "$firefox_artifact_path" ]; then
            echo "::error::Firefox artifact (.zip or .xpi) not found in build/ directory."
            exit 1
          fi
          echo "Found Firefox artifact: $firefox_artifact_path"
          echo "path=$firefox_artifact_path" >> $GITHUB_OUTPUT

      # КРОК 3: Завантажуємо артефакт для Firefox у щойно створений реліз
      - name: Upload Firefox Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # URL для завантаження
          asset_path: ${{ steps.get_firefox_path.outputs.path }}
          asset_name: xdAnswers-firefox-${{ github.ref_name }}.xpi
          asset_content_type: application/x-xpinstall

      # КРОК 4: Завантажуємо артефакт для Chrome у той самий реліз
      - name: Upload Chrome Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Використовуємо той самий URL
          # Шлях до архіву тепер фіксований завдяки нашому npm-скрипту
          asset_path: ./build/xdAnswers-chrome.zip
          asset_name: xdAnswers-chrome-${{ github.ref_name }}.zip
          asset_content_type: application/zip